### ISSUE TITLE
Developer tools setup guide on docs.swiftnav.com for OSX is broken

### ISSUE THREAD

**Issue by cbeighley** [swift-nav/piksi_firmware#103]
Piksi Console runs for a couple seconds then freezes entire system (OSX 10.9.4).

Used the following guide to install IPython, which also happened to fix the Piksi Console bug:

http://www.lowindata.com/2013/installing-scientific-python-on-mac-os-x/

**Comment by fnoble** [comment]
Think this is now superseded by @mookerji 's `setup.sh` script
