### ISSUE TITLE
Exception in tracking window drawing on OSX

### ISSUE THREAD

**Issue by cbeighley** [swift-nav/piksi_firmware#108]
Running the Piksi Console from source on commit 28b60fe50e612df88a2c3bc83cf38ce573a84023 in OSX 10.9.

![screen shot 2014-09-23 at 12 59 33 pm 2](https://cloud.githubusercontent.com/assets/502385/4378962/abb3904e-435c-11e4-8efc-c4aae4b46e26.png)

**Comment by fnoble** [comment]
This is now fixed by the `setup.sh` script.
