### ISSUE TITLE
Console - 'Settings' tab descriptions

### ISSUE THREAD

**Issue by drewshannon** [swift-nav/piksi_firmware#173]
When a user clicks a metric within the Settings tab of the console, have a description of the metric appear in the blank area to the right (see attached screenshot).
![5](https://cloud.githubusercontent.com/assets/9704961/5019643/3301a762-6a76-11e4-8caf-913489f275b9.png)

**Comment by denniszollo** [comment]
Merge commit: 9dac58bd0e025bde1274055092c904fa71aa0e77
Includes features that close this issue.
