### ISSUE TITLE
v0.15 release

### ISSUE THREAD

**Issue by cbeighley** [swift-nav/piksi_firmware#294]

**Comment by cbeighley** [comment]
Take stable master from last Wednesday without Gareth's 20ms changes, set up Jenkins job to test in HITL, have Dennis test immediately.

@gsmcmullin @denniszollo

**Comment by gsmcmullin** [comment]
Release branch created:
https://github.com/swift-nav/piksi_firmware/tree/v0.15-branch

**Comment by gsmcmullin** [comment]
Jenkins job created:
http://zazu.ci.swiftnav.com/job/piksi_firmware_Release/

@denniszollo please use these build artifacts for field testing.

**Comment by gsmcmullin** [comment]
HITL configured to use head of v0.15-branch.

**Comment by gsmcmullin** [comment]
Release finally made it out!
