### ISSUE TITLE
Shouldn't keep tracking unhealthy satellites

### ISSUE THREAD

**Issue by henryhallam** [swift-nav/piksi_firmware#3]
PRN 30 (SVN 35) is [on the fritz](http://thenogspot.blogspot.com/2011/08/recalled-svn-35-not-doing-well.html) and is currently marked as unhealthy.  Piksi correctly detects this, and doesn't use it in the navigation solution.  But it keeps tracking the satellite, wasting a channel.

Maybe this could be a configurable option as some users might be interested in the tracking data for unhealthy sats.

**Comment by fnoble** [comment]
Finally closed in #302!
