### ISSUE TITLE
setup.sh (via ansible playbook) fails to install 'construct', required by 'sbp'

### ISSUE THREAD

**Issue by henryhallam** [swift-nav/piksi_firmware#320]
Attempting to use 'setup.sh -x install' on a fresh machine (tested: Ubuntu 12.04, Debian Jessie) fails at 

TASK: [common_ubuntu | Install python Enthought dependencies]

[Full log](https://gist.github.com/henryhallam/5c637b3c0e43545dae29)

The problem appears to be that the '[construct](https://pypi.python.org/pypi/construct)' package is needed by '[sbp](https://pypi.python.org/pypi/sbp/0.27)''s setup.py - it is not merely a runtime dependency of the package.  In Debian parlance it might be considered a 'Pre-Depends'.  The ansible playbook lists both 'construct' and 'sbp' in the same invocation of 'pip install' (setup/ansible/roles/common_ubuntu/tasks/sys_deps.yml line 55):
```
pip install traits traitsui pyserial pylibftdi
             pyparsing==1.5.7 pygments intelhex six construct sbp==0.27
```

pip 'collects' (i.e. downloads) the tarball for each package, in the order given, but does not attempt to install them in the same order.

As a workaround, running 'sudo pip install construct' and rerunning setup.sh will do the job.

**Comment by mfine** [comment]
There was a dependency issue with construct and pulling the version of `sbp` - was resolved by https://github.com/swift-nav/libsbp/pull/75. Potentially this issue is no longer a problem with `sbp==0.29`.
