### ISSUE TITLE
PVT solver rejects solutions with negative altitude

### ISSUE THREAD

**Issue by henryhallam** [swift-nav/piksi_firmware#339]
This is a problem when receiver is near sea level (or ellipsoid level or whatever)
```
WARNING: PVT solver: Altitude unreasonable (-2)
```

**Comment by fnoble** [comment]
Unfortunately swift-nav/libswiftnav#117 doesn't actually fix this.

Have since verified the PVT solver is fine with a negative altitude (at least ~ -10m) so going to leave this closed unless @henryhallam you think there is still an issue here?

**Comment by henryhallam** [comment]
Nope, I'll believe it was functioning as designed and I just misinterpreted what I saw.
