### ISSUE TITLE
Autopilot Integration Documentation: Pixhawk <-> Piksi Docs

### ISSUE THREAD

**Issue by njoubert** [swift-nav/piksi_firmware#34]
Explain to people how to connect this as a primary or secondary GPS for Pixhawk.

Mention the DF13 cable that ships with Piksi is NOT APPROPRIATE for going into Pixhawk - the TX/RX needs to be flipped!

**Comment by soulcmdc** [comment]
@njoubert @denniszollo Is this issue taken care of?

**Comment by denniszollo** [comment]
Yes we can close this, but we do need to track down the cable issue.  @drewshannon Do you know how many of the incorrect cables we shipped?

**Comment by soulcmdc** [comment]
Completed per @denniszollo
