### ISSUE TITLE
Remove scripts directory and move towards piksi_tools

### ISSUE THREAD

**Issue by mfine** [swift-nav/piksi_firmware#349]
`piksi_tools` encompasses all of the content of scripts. Remove the scripts directory and update relevant documentation.

**Comment by cbeighley** [comment]
Let's make sure to merge any remaining scripts updates from piksi_firmware/v0.15-branch and piksi_firmware/master before this happens. I know there are updates in piksi_firmware/v0.15-branch (I'll be merging these into master today).

**Comment by mfine** [comment]
Noted - outstanding pull requests have been given feedback about the pending changes. Will hold off killing the directory until those changes are merged in.

**Comment by mfine** [comment]
All outstanding pull requests are in.

**Comment by mfine** [comment]
Next steps are to move jenkins on to `piksi_tools`.
