### ISSUE TITLE
RTCM output not working (reported by users)

### ISSUE THREAD

**Issue by denniszollo** [swift-nav/piksi_firmware#376]
Multiple users are reporting issues getting RTCM output to work.  We need to investigate and perhaps repair the issue.  See forum post below:
https://groups.google.com/forum/#!topic/swiftnav-discuss/bJ8ZWlStrvQ

**Comment by fnoble** [comment]
Yeah, we should remove this option, it was never finished.

**Comment by Matioupi** [comment]
I hope you will choose the repair option and not the remove one...
I think that interroperability is a must in the world of GNSS (I even hope that one day, piksies will be able to digest RTCM as input stream...)
