### ISSUE TITLE
Test 20ms tracking with higher SNR threshold

### ISSUE THREAD

**Issue by fnoble** [swift-nav/piksi_firmware#383]

**Comment by cbeighley** [comment]
Testing seems good with current threshold, however Stanislaw Nanek has reported the following error, which he thinks is related to tracking satellites with low C/N0:

'I also noticed that the pixie is tracking satellites with a small C/N0, which does not track before(probably),
 which result in a warning ["WARNING: PVT solver: Altitude unreasonable (-2)"]'

 * https://groups.google.com/forum/#!topic/swiftnav-discuss/5p0x_TlFUy8

And:

'Now I'm sure. keeps track of the satellite that is not on the horizon - this is Bug'

Dennis and I also observed the 'Altitude unreasonable' warning in our manual testing (not sure if this is actually related to the tracking C/N0. We may want to play with upping the threshold a bit.
