### ISSUE TITLE
Investigate & fix dgnss_baseline error returned -2, 

### ISSUE THREAD

**Issue by denniszollo** [swift-nav/piksi_firmware#540]

**Comment by fvantienen** [comment]
Any update on this?

**Comment by scottswift** [comment]
I'm working on it and expect it to be fixed in the next few weeks.

**Comment by denniszollo** [comment]
Firmware Version 0.21 fixes the root cause of the issues.  It remains that sometimes there are issues in the observations that prevent an RTK solution, but the -2 error can no longer  occur.
