### ISSUE TITLE
Excessive unnecessary calls to printf via sid_to_string

### ISSUE THREAD

**Issue by jacobmcnamee** [swift-nav/piksi_firmware#593]
Preemptively printing out the sid string at the top of a function is wasteful:

```
char buf[SID_STR_LEN_MAX];
sid_to_string(buf, sizeof(buf), ch->sid);

if (<first unlikely condition>)
  log("error: %s", buf);

if (<second unlikely condition>)
  log("error: %s", buf);
```

**Comment by ljbade** [comment]
@jacobmcnamee I did this to avoid copy/pasting code and to use principles of reuse.

If you think the performance overhead is significant then we can go back to copying the code in several places.

**Comment by jacobmcnamee** [comment]
Yeah, I understand the reasoning. But that's a lot of printfs that we rarely need. Especially in places like the tracking thread.

**Comment by ljbade** [comment]
@jacobmcnamee Yeah OK move the extra printfs out of the high perf threads like tracking. For other low priority threads I think they can be left.

**Comment by jacobmcnamee** [comment]
How about
```
#define _LOG_SID(func, sid, format, ...) { \
  char sid_str[SID_STR_LEN_MAX]; \
  sid_to_string(sid_str, sizeof(sid_str), sid); \
  log_error("%s" format, sid_str, ##__VA_ARGS__); \
}

#define log_warn_sid(sid, format, ...) \
  _LOG_SID(log_warn, sid, format, ##__VA_ARGS__)
```

Then you can do
```
log_warn_sid(sid, "something bad happened");
```
or
```
log_warn_sid(sid, "return code: %d", code);
```

**Comment by ljbade** [comment]
Hmm yeah that could work. Would prefer to not use a macro tho as they can be misleading as it looks like a real function.

However perhaps http://stackoverflow.com/questions/24814570/can-i-add-new-format-specifier-type-to-c-printf-in-linux-platform might work...

**Comment by jacobmcnamee** [comment]
swift-nav/libswiftnav#319
#632
