### ISSUE TITLE
Confine bit polarity to decoder

### ISSUE THREAD

**Issue by jacobmcnamee** [swift-nav/piksi_firmware#605]
Decoder should consider bit polarity in TOW calculation and not explicitly inform the tracking channel. 

Define a reference point for time sync: e.g. synced time applies to the leading edge of the most recently received nav bit.

**Comment by ljbade** [comment]
Hmm what does the current code do? I never understood the bit polarity stuff that is passed around.

**Comment by jacobmcnamee** [comment]
Upon further consideration, I don't believe this abstraction is possible.
