### ISSUE TITLE
Change nav bit half cycle slip message to a warning

### ISSUE THREAD

**Issue by ljbade** [swift-nav/piksi_firmware#609]
@denniszollo requested that the current error level message that is produced when there is a navigation bit flip, be changed to a warning as it is not a major problem.

This also interferes with HITL screaming death test results

**Comment by jacobmcnamee** [comment]
Fixed https://github.com/swift-nav/libswiftnav/pull/331

**Comment by ljbade** [comment]
Thanks, I forgot about this issue
