### ISSUE TITLE
Race condition with lock counter check in low latency mode

### ISSUE THREAD

**Issue by jacobmcnamee** [swift-nav/piksi_firmware#696]
It is possible to use local and/or base observations with changed lock counters in `output_baseline()` if the solution thread executes before the associated satellites can be dropped from the filters in the time matched observations thread.

**Comment by ljbade** [comment]
@denniszollo We should check this in our changes to the lock time counter for new SBP message

**Comment by ljbade** [comment]
Now that I think about it, this could be what causes the weird outliers
